spring.application.name=user-service

jwt.secretKey = dXNlci1kZXZlbG9wbWVudC1kdW1teS1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcw==
server.servlet.context-path=/users
server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Rapi@123
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone = http://localhost:8761/eureka