spring.application.name=posts-service

server.port=9010

spring.datasource.url=jdbc:postgresql://localhost:5432/postsDB?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Rapi@123
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone = http://localhost:8761/eureka